@startchen er_v2

left to right direction

entity User {
    user_id : String <<key>>
    name : String
}

entity EuroCoinCollectionGroup {
    group_id : String <<key>>
    name : String
    owner_id : String <<foreign_key>>
}

entity EuroCoinCollection {
    collection_id : String <<key>>
    name : String
    group_id : String <<foreign_key>>
}

entity EuroCoin {
    coin_id : String <<key>>
    year : Integer
    coin_value : Integer
    mint_country : String
    mint : String
    description : String
    collection_id : String <<foreign_key>>
}

relationship Owns {
}

Owns -1- User
Owns -N- EuroCoinCollectionGroup

relationship Contains {
}

Contains -1- EuroCoinCollectionGroup
Contains -N- EuroCoinCollection

relationship Holds {
}

Holds -1- EuroCoinCollection
Holds -N- EuroCoin

@endchen